from datetime import date

# 30 Eylül 2026'ya kadar geçerli BIST 50
BIST50_Q3_2026 = [
    "AEFES.IS",
    "AKBNK.IS",
    "AKSEN.IS",
    "ALARK.IS",
    "ASELS.IS",
    "ASTOR.IS",
    "BIMAS.IS",
    "BRSAN.IS",
    "BTCIM.IS",
    "CANTE.IS",
    "CCOLA.IS",
    "CIMSA.IS",
    "DSTKF.IS",
    "ECILC.IS",
    "EFOR.IS",
    "EKGYO.IS",
    "ENKAI.IS",
    "EREGL.IS",
    "FROTO.IS",
    "GARAN.IS",
    "GLRMK.IS",
    "GUBRF.IS",
    "HALKB.IS",
    "HEKTS.IS",
    "ISCTR.IS",
    "KCHOL.IS",
    "KRDMD.IS",
    "KTLEV.IS",
    "KUYAS.IS",
    "MGROS.IS",
    "MIATK.IS",
    "OYAKC.IS",
    "PASEU.IS",
    "PETKM.IS",
    "PGSUS.IS",
    "SAHOL.IS",
    "SASA.IS",
    "SISE.IS",
    "TAVHL.IS",
    "TCELL.IS",
    "THYAO.IS",
    "TOASO.IS",
    "TRALT.IS",
    "TRMET.IS",
    "TTKOM.IS",
    "TUPRS.IS",
    "TURSG.IS",
    "ULKER.IS",
    "VAKBN.IS",
    "YKBNK.IS",
]


# 1 Ekim - 31 Aralık 2026 BIST 50
BIST50_Q4_2026 = [
    "AEFES.IS",
    "AKBNK.IS",
    "AKSEN.IS",
    "ALARK.IS",
    "ASELS.IS",
    "ASTOR.IS",
    "BIMAS.IS",
    "BRSAN.IS",
    "BTCIM.IS",
    "CCOLA.IS",
    "CIMSA.IS",
    "CVKMD.IS",
    "CWENE.IS",
    "DOAS.IS",
    "DOHOL.IS",
    "ECILC.IS",
    "EKGYO.IS",
    "ENERY.IS",
    "ENKAI.IS",
    "EREGL.IS",
    "FROTO.IS",
    "GARAN.IS",
    "GLRMK.IS",
    "GUBRF.IS",
    "HALKB.IS",
    "HEKTS.IS",
    "ISCTR.IS",
    "KCHOL.IS",
    "KRDMD.IS",
    "MAVI.IS",
    "MGROS.IS",
    "OYAKC.IS",
    "PETKM.IS",
    "PGSUS.IS",
    "SAHOL.IS",
    "SASA.IS",
    "SISE.IS",
    "SOKM.IS",
    "TAVHL.IS",
    "TCELL.IS",
    "THYAO.IS",
    "TOASO.IS",
    "TRALT.IS",
    "TRMET.IS",
    "TSKB.IS",
    "TTKOM.IS",
    "TUPRS.IS",
    "TURSG.IS",
    "ULKER.IS",
    "VAKBN.IS",
    "YKBNK.IS",
]


# Tarihe göre doğru listeyi otomatik seç
if date.today() >= date(2026, 10, 1):
    STOCKS = BIST50_Q4_2026
else:
    STOCKS = BIST50_Q3_2026